<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>PhysicalLightandCameraUnits</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="src/XPrimeRay.Core/**/*.cs" />
    <Compile Remove="src/XPrimeRay.Testbench.Cli/**/*.cs" />
    <Compile Remove="src/XPrimeRay.ObserverInstrumentation/**/*.cs" />
    <Compile Remove="src/XPrimeRay.ObserverInstrumentation.Tests/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="src/XPrimeRay.ObserverInstrumentation/XPrimeRay.ObserverInstrumentation.csproj" />
  </ItemGroup>
</Project>
