<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>XPrimeRay.Spatial</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../XPrimeRay.Core/XPrimeRay.Core.csproj" />
  </ItemGroup>
</Project>
