#!/usr/bin/env python3
"""Render the Difference Packet Gallery from its structured exhibit index."""

from __future__ import annotations

import json
import os
import sys
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any


REQUIRED_TOP_LEVEL = ("indexId", "title", "version", "generatedUtc", "entries", "claimBoundary")
REQUIRED_ENTRY = (
    "id",
    "title",
    "sourceCase",
    "status",
    "rule",
    "reason",
    "leftFixture",
    "rightFixture",
    "leftChannel",
    "rightChannel",
    "comparisonMode",
    "parityClaim",
    "runtimeExecuted",
    "metrics",
    "claimBoundary",
)
REQUIRED_METRICS = ("countCompared", "maxAbsDifference", "meanAbsDifference", "nonZeroCount")
STATUS_ORDER = ("Comparable", "NotComparable", "RequiresTransform", "Unknown")


def require_fields(value: dict[str, Any], fields: tuple[str, ...], context: str) -> None:
    missing = [field for field in fields if field not in value]
    if missing:
        raise ValueError(f"{context}: missing required field(s): {', '.join(missing)}")


def load_index(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"index not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path}:{exc.lineno}:{exc.colno}: invalid JSON: {exc.msg}") from exc

    if not isinstance(data, dict):
        raise ValueError("index: expected a JSON object")
    require_fields(data, REQUIRED_TOP_LEVEL, "index")
    if not isinstance(data["entries"], list) or not data["entries"]:
        raise ValueError("index.entries: expected a non-empty array")
    if not isinstance(data["claimBoundary"], list) or not data["claimBoundary"]:
        raise ValueError("index.claimBoundary: expected a non-empty array")

    seen: set[str] = set()
    for position, entry in enumerate(data["entries"]):
        context = f"index.entries[{position}]"
        if not isinstance(entry, dict):
            raise ValueError(f"{context}: expected an object")
        require_fields(entry, REQUIRED_ENTRY, context)
        entry_context = f"{context} id='{entry.get('id', '<missing>')}'"
        if entry["parityClaim"] != "NONE":
            raise ValueError(
                f"{entry_context}.parityClaim: expected 'NONE', got {entry['parityClaim']!r}"
            )
        if entry["runtimeExecuted"] is not False:
            raise ValueError(
                f"{entry_context}.runtimeExecuted: expected false, got {entry['runtimeExecuted']!r}"
            )
        if entry["comparisonMode"] != "core_vs_core":
            raise ValueError(
                f"{entry_context}.comparisonMode: expected 'core_vs_core', got {entry['comparisonMode']!r}"
            )
        require_fields(entry["metrics"], REQUIRED_METRICS, f"{context}.metrics")
        if entry["id"] in seen:
            raise ValueError(f"{context}.id: duplicate exhibit id '{entry['id']}'")
        seen.add(entry["id"])
        if entry["status"] not in STATUS_ORDER:
            raise ValueError(f"{context}.status: unsupported status '{entry['status']}'")
        if not isinstance(entry["claimBoundary"], list) or not entry["claimBoundary"]:
            raise ValueError(f"{context}.claimBoundary: expected a non-empty array")

    return data


def format_number(value: Any) -> str:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise ValueError(f"metric value must be numeric, got {value!r}")
    return str(value)


def render(index: dict[str, Any]) -> str:
    entries = index["entries"]
    counts = Counter(entry["status"] for entry in entries)
    lines = [
        "# Project Glowing Heart v2.4 Difference Packet Gallery",
        "",
        "<!-- Generated by tools/glowing_heart_gallery_renderer.py. Do not edit exhibit values by hand. -->",
        "",
        f"Rendered from `{index['indexId']}` version `{index['version']}`.",
        "",
        "## How to Read This Gallery",
        "",
        "- `Comparable` means the declared eligibility conditions passed.",
        "- `Unknown` means eligibility was not established, so values were not compared.",
        "- `NotComparable` means the compatibility matrix declares the channel pair incompatible.",
        "- `RequiresTransform` means comparison needs a declared transform first.",
        "",
        "These statuses describe comparison eligibility, not scientific correctness.",
        "",
        "## Status Summary",
        "",
        "| Status | Exhibits |",
        "|---|---:|",
    ]
    lines.extend(f"| `{status}` | {counts.get(status, 0)} |" for status in STATUS_ORDER)

    for entry in entries:
        metrics = entry["metrics"]
        lines.extend(
            [
                "",
                f"## {entry['title']}",
                "",
                "| Field | Value |",
                "|---|---|",
                f"| Exhibit ID | `{entry['id']}` |",
                f"| Source case | {entry['sourceCase']} |",
                f"| Status | `{entry['status']}` |",
                f"| Rule | `{entry['rule']}` |",
                f"| Left fixture | `{entry['leftFixture']}` |",
                f"| Right fixture | `{entry['rightFixture']}` |",
                f"| Left channel | `{entry['leftChannel']}` |",
                f"| Right channel | `{entry['rightChannel']}` |",
                f"| Count compared | {format_number(metrics['countCompared'])} |",
                f"| Maximum absolute difference | {format_number(metrics['maxAbsDifference'])} |",
                f"| Mean absolute difference | {format_number(metrics['meanAbsDifference'])} |",
                f"| Non-zero count | {format_number(metrics['nonZeroCount'])} |",
                "",
                f"**What this shows:** {entry['reason']}",
                "",
                "**What this does not show:**",
                "",
            ]
        )
        lines.extend(f"- {boundary}" for boundary in entry["claimBoundary"])

    lines.extend(["", "## Claim Boundary", ""])
    lines.extend(f"- {boundary}" for boundary in index["claimBoundary"])
    lines.extend(
        [
            "",
            "## Future Tooling",
            "",
            "The structured index can also drive tables, matrices, cards, and Atlas Graph nodes without parsing this Markdown.",
            "",
        ]
    )
    return "\n".join(lines)


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(f"Usage: {argv[0]} <index.json> <preview.md> <docs.md>", file=sys.stderr)
        return 2

    index_path, preview_path, docs_path = map(Path, argv[1:])
    resolved = [path.resolve() for path in (index_path, preview_path, docs_path)]
    if len(set(resolved)) != 3:
        print("Error: index and output paths must be distinct.", file=sys.stderr)
        return 2

    try:
        markdown = render(load_index(index_path))
        write_atomic(preview_path, markdown)
        write_atomic(docs_path, markdown)
    except (OSError, TypeError, ValueError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    print(f"PASS: rendered {preview_path} and {docs_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
